# Exported from Render on 2025-07-14T14:49:24Z
databases:
- name: orangejuicebank-db
  databaseName: orangejuicebank_83ws
  user: orangejuicebank_83ws_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"


databases:
  - name: orangejuicebank-db
    databaseName: orangejuicebank
    plan: free
    region: ohio

