services:
  - type: web
    name: orangejuicebank-frontend
    env: docker
    repo: https://github.com/priscillatrevizan/orange-juice-bank
    region: ohio
    branch: main
    rootDir: ./frontend
    dockerfilePath: ../Dockerfile
    buildFilter:
      paths:
        - frontend/*
    envVars:
      - key: VITE_API_URL
        value: http://orangejuicebank-backend:3000/api/v1
    plan: free

  - type: web
    name: orangejuicebank-backend
    env: docker
    repo: https://github.com/priscillatrevizan/orange-juice-bank
    region: ohio
    branch: main
    rootDir: ./backend
    dockerfilePath: ../Dockerfile
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orangejuicebank-db
          property: connectionString
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
    plan: free

databases:
  - name: orangejuicebank-db
    databaseName: orangejuicebank
    user: postgres
    plan: free
    region: ohio
