version: "1"
services:
  - type: web
    name: orangejuicebank-frontend
    runtime: static
    repo: https://github.com/priscillatrevizan/orange-juice-bank
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://orangejuicebank-backend.onrender.com/api/v1

  - type: web
    name: orangejuicebank-backend
    runtime: node
    repo: https://github.com/priscillatrevizan/orange-juice-bank
    branch: main
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orangejuicebank-db
          property: connectionString
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: orangejuicebank-db
    databaseName: orangejuicebank
    plan: free
