version: "1"

services:
  - type: web
    name: orangejuicebank-frontend
    env: docker
    repo: https://github.com/priscillatrevizan/orange-juice-bank
    region: ohio
    branch: main
    rootDir: ./frontend
    dockerfilePath: ../Dockerfile
    buildFilter:
      paths:
        - frontend/*
    envVars:
      - key: VITE_API_URL
        value: http://orangejuicebank-backend:3000/api/v1
    plan: free

  - type: web
    name: orangejuicebank-backend
    env: docker
    repo: https://github.com/priscillatrevizan/orange-juice-bank
    region: ohio
    branch: main
    rootDir: ./backend
    dockerfilePath: ../Dockerfile
    buildCommand: npm install && npx prisma g
